[package]
name = "tunacode-git-tooling"
version.workspace = true
edition.workspace = true
readme = "README.md"

[lib]
name = "tunacode_git_tooling"
path = "src/lib.rs"

[dependencies]
tempfile = "3"
thiserror = "2"
walkdir = "2"

[lints]
workspace = true

[dev-dependencies]
pretty_assertions = "1.4.1"
