name: Publish to PyPI

"on":
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install build tooling
        run: |
          python -m pip install --upgrade pip
          pip install hatch twine uv

      - name: Determine version from tag
        id: ver
        shell: bash
        run: |
          # Prefer release tag when present; fall back to ref name
          if [ "${{ github.event_name }}" = "release" ]; then
            TAG="${{ github.event.release.tag_name }}"
          else
            TAG="${{ github.ref_name }}"
          fi
          TAG="${TAG#v}"
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"

      - name: Check version consistency
        shell: bash
        run: |
          TAG="${{ steps.ver.outputs.tag }}"
          PYPROJ=$(sed -n 's/^version = "\(.*\)"/\1/p' pyproject.toml)
          CONST=$(sed -n 's/^APP_VERSION = "\(.*\)"/\1/p' src/tunacode/constants.py)
          echo "Tag: $TAG"
          echo "pyproject.toml: $PYPROJ"
          echo "constants.APP_VERSION: $CONST"
          if [[ "$TAG" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            [[ "$TAG" == "$PYPROJ" ]] || { echo 'pyproject.toml version mismatch'; exit 1; }
            [[ "$TAG" == "$CONST" ]] || { echo 'constants.py APP_VERSION mismatch'; exit 1; }
          else
            echo "No semver tag detected; skipping tag consistency check."
          fi

      - name: Lint
        run: hatch run lint-check

      - name: Test
        run: hatch run test

      - name: Build
        run: hatch build

      # Preferred: API token secret
      - name: Publish to PyPI (API token)
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: python -m twine upload dist/*

      # Fallback: username/password secrets
      - name: Publish to PyPI (user/pass)
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: python -m twine upload dist/*
